AuthenticationAndAuthorisation-hw/Models/AccountBindingModels.cs
using System.ComponentModel.DataAnnotations;

namespace AuthenticationAndAuthorization_hw.Models
{
    public class RegisterBindingModel
    {
        [Required]
        public string Login {  get; set; }

        [Required]
        [UIHint("Password")]
        public string Password {  get; set; }

        [Required]
        [Compare("Password")]
        [Display(Name = "Confirm password")]
        [UIHint("Password")]
        public string PasswordConfirm { get; set; }
    }


    public class AuthorizeBindingModel
    {
        [Required]
        public string Login { get; set; }

        [Required]
        [UIHint("Password")]
        public string Password { get; set; }
    }
}

AuthenticationAndAuthorisation-hw/Models/ErrorViewModel.cs
namespace AuthenticationAndAuthorization_hw.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AuthenticationAndAuthorisation-hw/Models/NoteBinding.cs
using System.ComponentModel.DataAnnotations;

namespace AuthenticationAndAuthorization_hw.Models
{
    public class NoteBinding
    {
        public string Tittle {  get; set; }

        [Required]
        public string Content {  get; set; }
    }
}

AuthenticationAndAuthorisation-hw/Controllers/AccountController.cs
using AuthenticationAndAuthorization_hw.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using AuthenticationAndAuthorization_hw.Logic;
using AuthenticationAndAuthorization_hw.Logic.Account;

namespace AuthenticationAndAuthorization_hw.Controllers
{
    public class AccountController : Controller
    {
        private PseudoDatabase _db;

        public AccountController(PseudoDatabase db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(RegisterBindingModel model)
        {
            if (ModelState.IsValid)
            {
                bool loginIsUnique = !_db.Users.Any(u => u.Login == model.Login);
                if (loginIsUnique)
                {
                    var newUser = new User
                    {
                        Id = Guid.NewGuid(),
                        Login = model.Login,
                        Salt = Guid.NewGuid(),
                    };
                    newUser.PasswordHash = PasswordHasher.HashPassword(model.Password + newUser.Salt.ToString());
                    _db.Users.Add(newUser);
                    await SignInAsync(newUser);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(nameof(model.Login), "This Login is already in use :(");
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }

        }


        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(AuthorizeBindingModel model)
        {

            if (ModelState.IsValid)
            {
                var userOrNull = _db.Users.FirstOrDefault(x => x.Login == model.Login);
                if (userOrNull is User user)
                {
                    var isCorrectPassword = PasswordHasher.IsCorrectPassword(user, model.Password);
                    if (isCorrectPassword)
                    {
                        await SignInAsync(user);
                        return RedirectToAction("Index", "Home");
                    }
                }
                ModelState.AddModelError("", "Wrong login or password");
                return View(model);
            }
            else
            {
                return View(model);
            }
        }

        public async Task<IActionResult> SignOut()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        private async Task SignInAsync(User user)
        {
            var claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, user.Login),
                new Claim(ClaimTypes.Role, "User"),
            };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
            var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
            await HttpContext.SignInAsync(claimsPrincipal);
        }
    }
}

AuthenticationAndAuthorisation-hw/Controllers/HomeController.cs
using AuthenticationAndAuthorization_hw.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AuthenticationAndAuthorization_hw.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View(User.Identity.Name as object);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AuthenticationAndAuthorisation-hw/Controllers/NotesController.cs
using AuthenticationAndAuthorization_hw.Logic;
using AuthenticationAndAuthorization_hw.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AuthenticationAndAuthorization_hw.Controllers
{
    public class NotesController : Controller
    {
        private PseudoDatabase _db;

        public NotesController(PseudoDatabase db)
        {
            _db = db;
        }
        [Authorize]
        public IActionResult Add()
        {
            return View();
        }
        
        [Authorize]
        [HttpPost]
        public IActionResult Add(NoteBinding model)
        {
            var currentUserId = _db.Users.FirstOrDefault(u => u.Login == User.Identity.Name).Id;
            if (currentUserId == null)
            {
                throw new NullReferenceException("can't find user with such name like authorized user");
            }
            _db.Notes.Add(
                new Logic.Notes.Note
                {
                    Tittle = model.Tittle,
                    Content = model.Content,
                    OwnerId = currentUserId
                });
            return View();
        }
        [Authorize]
        public IActionResult All()
        {
            var currentUserId = _db.Users.FirstOrDefault(u => u.Login == User.Identity.Name).Id;
            if (currentUserId == null)
            {
                throw new NullReferenceException("can't find user with such name like authorized user");
            }
            var currentUserNotes = _db.Notes.Where(n => n.OwnerId == currentUserId).ToList();
            return View(currentUserNotes);
        }
    }
}

AuthenticationAndAuthorisation-hw/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    @if (String.IsNullOrEmpty(Model))
    {
        <p>
            You can't do anything without the registration or authorization so...
        </p>
        <a asp-action="SignIn" , asp-controller="Account">Sign in</a>
        <a asp-action="SignUp" , asp-controller="Account">Sign up</a>
    }
    else
    {
        <h2 class="display-4">@Model</h2>
    }
</div>

AuthenticationAndAuthorisation-hw/Views/Notes/Add.cshtml
@model AuthenticationAndAuthorization_hw.Models.NoteBinding
@{
    ViewData["Title"] = "Create new note";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create note</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="card-body">
    <div class="col-md-4">
        <h1 class="display-4">Welcome</h1>
        <form asp-action="Add">
            <div class="form-group">
                <label asp-for="Tittle" class="control-label"></label>
                <input asp-for="Tittle" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control" ></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Add note" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

</body>
</html>

AuthenticationAndAuthorisation-hw/Views/Notes/All.cshtml
@model List<AuthenticationAndAuthorization_hw.Logic.Notes.Note>
@{
    ViewData["Title"] = "Registration Page";
}
<div class="display-notes">
@if (Model.Any())
{

    foreach(var note in Model)
    {
        <div>
            <h4>@note.Tittle</h4>
            <br />
            <p>@note.Content</p>
        </div>
        
    }
}
else
{
    <h2>You've not created any notes yet</h2>
}
</div>

AuthenticationAndAuthorisation-hw/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuthenticationAndAuthorization_hw</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuthenticationAndAuthorization_hw.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AuthenticationAndAuthorization_hw</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notes" asp-action="Add">Create note</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notes" asp-action="All">All your notes</a>
                        </li>
                    </ul>
                </div>
                <a class="nav-link text-light out-btn" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AuthenticationAndAuthorisation_hw - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>